name: CI
on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Main_CI:
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        shell: bash
        run: |
          echo "testing job on Main CI"
