name: Create Release

on:
  push:
    branches:
      - 'releases/**'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        commit: ${{ GITHUB_REF }}
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
