name: Create Release

on:
  push:
    branches:
      - 'releases/**'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        commit: ${{ github.sha }}
        draft: true
        bodyFile: ".github/release_template.md"
        name: "NI gRPC Device Server #.#.#"
        tag: "vx.x.x"
        token: ${{ secrets.GITHUB_TOKEN }}
