name: Create Release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: "Create Release"
      uses: ncipollo/release-action@v1
      if: ${{ startsWith(github.ref, 'refs/heads/releases') }}
      with:
        commit: ${{ github.sha }}
        draft: true
        bodyFile: ".github/release_template.md"
        name: "NI gRPC Device Server #.#.#"
        tag: "vx.x.x"
        token: ${{ secrets.GITHUB_TOKEN }}
